### ISSUE TITLE
Location for config links

### ISSUE THREAD

**Issue by jpadfield** [E-RIHS/controlled-lists#2]
I am looking at adding some links to display the tool config and refresh the tool config based on new groups.

This was done as a stepping stone to adding in new group handles in the config, the refresh options would create new entries in the config with blank handle values which at this time would just need to be added in by hand.

Now the question was if I am making the config link(s) visible and if so where to out them?

I was think jus next the header:

![FireShot Capture 025 - E-RIHS Controlled List Links - round4 ng-london org uk](https://github.com/E-RIHS/controlled-lists/assets/17745845/ffcdcc7b-133a-4ee0-8299-88e9ea35bbd1)

What do you think?

**Comment by jpadfield** [comment]
New groups are added into the json like:

```json
    "g48": {
    "id": "g48",
    "label": "Data Type",
    "handle": false,
    "url": "https://research.ng-london.org.uk/ecls/?group=g48"
},
```

Or technically the URL is set relative to where the tool is running so if the tool is running on a different machine the **new** **url** would automatically appear as:

```json
    "url": "https://myownsite.org.uk/?group=g48"
```

**Comment by jpadfield** [comment]
I was not taking it that far :-)
The tool will just create the new file ready to be updated and saved on GitHub.

The tool looks for new groups on OpenTheso, if it finds some it adds new placeholder sections in a new temporary version of the config file. The file is not saved anywhere, it is just displayed.

You would need to copy it, edit it to add in the new handles, and then save it to GitHub.

I might then need to pull the new config file down to the live machine.

**Comment by kobbejager** [comment]
ah ok :-).
Next to the header title seems fine with me.
